/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : string,
  'principal' : Principal,
  'balance' : number,
  'name' : string,
  'address' : string,
  'phone' : string,
}
export interface CustomerPortalView {
  'unreadNotifications' : Array<Notification>,
  'customer' : Customer,
  'allTransactions' : Array<Transaction>,
  'pendingBalance' : number,
  'oldestToNewest' : Array<Transaction>,
}
export interface Notification {
  'id' : string,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Time,
  'shopName' : string,
  'customerId' : string,
}
export type PaymentType = { 'cash' : null } |
  { 'fullClear' : null } |
  { 'partial' : null } |
  { 'online' : null };
export type Time = bigint;
export interface Transaction {
  'id' : string,
  'weight' : number,
  'creator' : Principal,
  'balance' : number,
  'rate' : number,
  'timestamp' : Time,
  'shopName' : string,
  'paymentType' : PaymentType,
  'customerId' : string,
  'totalPrice' : number,
  'payment' : number,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'customerId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / *********
   * /    * Customer Management
   * /   ***********
   */
  'createCustomer' : ActorMethod<[string, string, string], string>,
  'createTransaction' : ActorMethod<
    [string, number, number, PaymentType, string],
    { 'remainingBalance' : number, 'transactionId' : string }
  >,
  'deleteCustomer' : ActorMethod<[string], undefined>,
  'deleteTransaction' : ActorMethod<[string], undefined>,
  'editTransaction' : ActorMethod<
    [string, number, number, PaymentType, string],
    undefined
  >,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentKgRate' : ActorMethod<[], number>,
  'getCustomer' : ActorMethod<[string], Customer>,
  /**
   * / *********
   * /    * Public Customer Portal (CustomerView)
   * /   ***********
   */
  'getCustomerPortalView' : ActorMethod<[string], [] | [CustomerPortalView]>,
  'getCustomerTransactions' : ActorMethod<[string], Array<Transaction>>,
  'getDailyStats' : ActorMethod<
    [string],
    { 'totalPayments' : number, 'totalSales' : number, 'totalBalance' : number }
  >,
  'getMonthlyStats' : ActorMethod<
    [string],
    { 'totalPayments' : number, 'totalSales' : number, 'totalBalance' : number }
  >,
  'getUnreadNotifications' : ActorMethod<[string], Array<Notification>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyStats' : ActorMethod<
    [string],
    { 'totalPayments' : number, 'totalSales' : number, 'totalBalance' : number }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationsRead' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / *********
   * /    * Notification System
   * /   ***********
   */
  'sendNotification' : ActorMethod<[string, string, string], string>,
  /**
   * / *********
   * /    * Admin-Configurable kgRate
   * /   ***********
   */
  'setKgRate' : ActorMethod<[number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];