/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentType = IDL.Variant({
  'cash' : IDL.Null,
  'fullClear' : IDL.Null,
  'partial' : IDL.Null,
  'online' : IDL.Null,
});
export const Customer = IDL.Record({
  'id' : IDL.Text,
  'principal' : IDL.Principal,
  'balance' : IDL.Float64,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'weight' : IDL.Float64,
  'creator' : IDL.Principal,
  'balance' : IDL.Float64,
  'rate' : IDL.Float64,
  'timestamp' : Time,
  'shopName' : IDL.Text,
  'paymentType' : PaymentType,
  'customerId' : IDL.Text,
  'totalPrice' : IDL.Float64,
  'payment' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'customerId' : IDL.Opt(IDL.Text),
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
  'shopName' : IDL.Text,
  'customerId' : IDL.Text,
});
export const CustomerPortalView = IDL.Record({
  'unreadNotifications' : IDL.Vec(Notification),
  'customer' : Customer,
  'allTransactions' : IDL.Vec(Transaction),
  'pendingBalance' : IDL.Float64,
  'oldestToNewest' : IDL.Vec(Transaction),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'createTransaction' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, PaymentType, IDL.Text],
      [
        IDL.Record({
          'remainingBalance' : IDL.Float64,
          'transactionId' : IDL.Text,
        }),
      ],
      [],
    ),
  'deleteCustomer' : IDL.Func([IDL.Text], [], []),
  'deleteTransaction' : IDL.Func([IDL.Text], [], []),
  'editTransaction' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, PaymentType, IDL.Text],
      [],
      [],
    ),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentKgRate' : IDL.Func([], [IDL.Float64], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [Customer], ['query']),
  'getCustomerPortalView' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CustomerPortalView)],
      ['query'],
    ),
  'getCustomerTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getDailyStats' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'totalPayments' : IDL.Float64,
          'totalSales' : IDL.Float64,
          'totalBalance' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getMonthlyStats' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'totalPayments' : IDL.Float64,
          'totalSales' : IDL.Float64,
          'totalBalance' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getUnreadNotifications' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyStats' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'totalPayments' : IDL.Float64,
          'totalSales' : IDL.Float64,
          'totalBalance' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationsRead' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendNotification' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'setKgRate' : IDL.Func([IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentType = IDL.Variant({
    'cash' : IDL.Null,
    'fullClear' : IDL.Null,
    'partial' : IDL.Null,
    'online' : IDL.Null,
  });
  const Customer = IDL.Record({
    'id' : IDL.Text,
    'principal' : IDL.Principal,
    'balance' : IDL.Float64,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'weight' : IDL.Float64,
    'creator' : IDL.Principal,
    'balance' : IDL.Float64,
    'rate' : IDL.Float64,
    'timestamp' : Time,
    'shopName' : IDL.Text,
    'paymentType' : PaymentType,
    'customerId' : IDL.Text,
    'totalPrice' : IDL.Float64,
    'payment' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'customerId' : IDL.Opt(IDL.Text),
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
    'shopName' : IDL.Text,
    'customerId' : IDL.Text,
  });
  const CustomerPortalView = IDL.Record({
    'unreadNotifications' : IDL.Vec(Notification),
    'customer' : Customer,
    'allTransactions' : IDL.Vec(Transaction),
    'pendingBalance' : IDL.Float64,
    'oldestToNewest' : IDL.Vec(Transaction),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'createTransaction' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, PaymentType, IDL.Text],
        [
          IDL.Record({
            'remainingBalance' : IDL.Float64,
            'transactionId' : IDL.Text,
          }),
        ],
        [],
      ),
    'deleteCustomer' : IDL.Func([IDL.Text], [], []),
    'deleteTransaction' : IDL.Func([IDL.Text], [], []),
    'editTransaction' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, PaymentType, IDL.Text],
        [],
        [],
      ),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentKgRate' : IDL.Func([], [IDL.Float64], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [Customer], ['query']),
    'getCustomerPortalView' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CustomerPortalView)],
        ['query'],
      ),
    'getCustomerTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getDailyStats' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'totalPayments' : IDL.Float64,
            'totalSales' : IDL.Float64,
            'totalBalance' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getMonthlyStats' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'totalPayments' : IDL.Float64,
            'totalSales' : IDL.Float64,
            'totalBalance' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getUnreadNotifications' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyStats' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'totalPayments' : IDL.Float64,
            'totalSales' : IDL.Float64,
            'totalBalance' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationsRead' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'setKgRate' : IDL.Func([IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };